Upload html report to pages

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -117,9 +117,49 @@ jobs:
           path: playwright-report
           retention-days: 14
 
+      - name: Check out reports branch
+        uses: actions/checkout@v4
+        with:
+          ref: reports
+          path: reports-branch
+          fetch-depth: 0
+
+      - name: Generate report name and URL
+        id: report-id
+        run: |
+          name=$(date +"%Y-%m-%d-%H-%M-%S")
+          echo "name=$name" >> $GITHUB_OUTPUT
+          echo "path=reports/$name" >> $GITHUB_OUTPUT
+          echo "url=https://github-playground-test-reports.netlify.app/$name/" >> $GITHUB_OUTPUT
+
+      - name: Copy html report and push reports branch
+        run: |
+          cp -r playwright-report reports-branch/${{ steps.report-id.outputs.path }}
+          cd reports-branch
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add reports
+          git commit -m "Add test report for run ${{ github.run_id }} (attempt: ${{ github.run_attempt }})"
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+
+      - name: Output report url
+        run: |
+          echo "::notice title=Published Playwright test report::${{ steps.report-id.outputs.url }}"
+
       - name: Create report comment
         id: report-summary
-        uses: daun/playwright-report-summary@v2.1.0
+        uses: daun/playwright-report-summary@v2.1.1
         with:
           report-file: results.json
           report-url: ${{ steps.report-id.outputs.url }}
